name: deploy-app
on:
  push:
    branches:
    - main
jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
    - name: clone the app code
      uses: actions/checkout@v4
    - name: run the tests
      run: echo "run tests for the app"
  deploy-app:
    needs: test-app
    runs-on: ubuntu-latest
    steps:
    - name: deploy the code
      run: echo "deploy the code"